### ISSUE TITLE
[question] The right way to expose admin-ui.

### ISSUE THREAD

**Issue by allomov** [cloudfoundry-incubator/admin-ui#123]
Just a question. 

What is the right way of exposing Admin UI? Is it possible to bind some domain to it, like `admin-ui.cloudfoundry-domain.com`? 

I though admin-ui has functional where it can tell router where admin-ui can be found, but for now I just can't find it.

Thank you,
Alex L.

**Comment by chrisrana** [comment]
Hi guys I am trying to access admin_ui from internet.It is redirecting
http://uaa.devtest3.io/oauth/authorize?response_type=code&client_id=admin_ui_client&redirect_uri=https://admin.devtest3.io/log 
and it is failing since 

Is admin_ui is not designed to access from internet ?

**Comment by allomov** [comment]
@chrisrana the problem could be in your UAA settings. could you tell how you installed admin_ui? did you use bosh-release for that? did you added it to UAA as it is described in [README](https://github.com/cloudfoundry-incubator/admin-ui#setup-administration-ui-group-and-user-using-uaac)?

**Comment by allomov** [comment]
@chrisrana the way you expose admin-ui is up to you, you can freely add access to it through internet. I guess your problem is more env specific and I would suggest to create new issue for that (if you deployed admin ui using bosh release, then create issue in the repo of bosh release).

**Comment by chrisrana** [comment]
I used bosh-release for admin deployment and I ran bosh run errand register_admin_ui this.
