### ISSUE TITLE
Health Managers tab shows no data

### ISSUE THREAD

**Issue by scotttag** [cloudfoundry-incubator/admin-ui#135]
Admin-ui seems to be working a treat and all the tabs seem to be working fine with accurate data, other than the Health Managers tab which shows no data

Is there an issue with regards to showing health manager status?

**Comment by rboykin** [comment]
Never have modified the Health Manager tab to consume information from the newer HM9000 Health Manager.  The tab that is there today works with the old Health Manager.  

As a result, showing no data is currently expected.

**Comment by scotttag** [comment]
Suspected that was the case, just wanted to make sure I wasn't doing something wildly wrong :-)

Thanks for confirming!
