### ISSUE TITLE
What is the VARZ class?

### ISSUE THREAD

**Issue by nnoco** [cloudfoundry-incubator/admin-ui#138]
Hi, all.

I found the VARZ class while analyzing admin-ui source code.
but I had no idea what is the VARZ class.
I tried to search for it, I could not find it.

Is there someone to explain that?

ps. I can't find mailing-list for admin-ui, so I write this question here.

**Comment by rboykin** [comment]
One of the data sources for the admin ui is the data from a CloudFoundry component's varz endpoints. The varz class in the admin ui provides for the gathering of this data from the components.

**Comment by nnoco** [comment]
Thanks a lot! may I ask one more? what is the short for VARZ?

**Comment by rboykin** [comment]
Guessing variables.  Base code for the vcap component including varz found here:  https://github.com/cloudfoundry/vcap-common/blob/master/lib/vcap/component.rb#L16

**Comment by nnoco** [comment]
Wow you are so kind, thank you for your answer :)
