### ISSUE TITLE
monit config reached memory limit

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry-incubator/admin-ui#143]
The monit configuration has a hard limit of 500 MB which is reached in some of our deployments. As result monit restarts the admin ui in endless loop.

https://github.com/cloudfoundry-community/admin-ui-boshrelease/blob/master/jobs/admin_ui/monit

I suggest to raise the limit to a higher value (500Mb -> 1Gb). A pull request will follow...

**Comment by rboykin** [comment]
This is not an issue with the admin ui, but the admin-ui-boshrelease as you reference.  PR not applicable here.

**Comment by sklevenz** [comment]
Sorry, I was on the wrong project. I am closing...
