### ISSUE TITLE
Next for adminui?

### ISSUE THREAD

**Issue by tomsherrod** [cloudfoundry-incubator/admin-ui#144]
I'm using adminui on a couple of installs and looking at a couple more.
The latest versions of CF are moving away from varz and nats. 
(http://bosh.io/releases/github.com/cloudfoundry/cf-release?version=220  "This is in service of deprecating the Collector and all /varz endpoints.")

Plans for adminui to evolve also or am I putting too much importance on the varz endpoints?

Thank you!

**Comment by rboykin** [comment]
Right now the Admin UI depends on the varz endpoints for the DEA, Cloud Controller, Health Manager, Router and App Instances tabs.  It also collates runtime information for orgs, spaces and apps from the DEA's varz information.  The information for the other tabs and the majority of info for orgs, spaces and apps comes from the CCDB/UAADB.

The Admin UI will eventually collect information from the varz replacement.  But, no work yet done there.

**Comment by chrisrana** [comment]
I am trying to deploy bosh release for adminUI. It is failing as "Can only target Bosh Lite Director. Please use 'bosh target' before running this script." when i run ./make_manifest warden i have installed cloud foundry using bosh.I have set the target and director name in my case is install-dev.

**Comment by rboykin** [comment]
Progress made here.  I have dropped commit https://github.com/cloudfoundry-incubator/admin-ui/commit/17de5285b16d948f74f0b10e9f8b69a5b6ce3937 to add support to retrieve information from the doppler_logging_endpoint websocket.  Currently only used to provide a Cells tab.  But, application instance metrics via the ContainerMetric coming.
