### ISSUE TITLE
Insufficient scope for user 

### ISSUE THREAD

**Issue by Yancey1989** [cloudfoundry-incubator/admin-ui#146]
When i install admin-ui follow README, I can login the web.there is an errro in the page:

Scope Error
Insufficient scope for user 

I deploy my cf with cf_nise_install and cf-release version is v217,  and there is an error msg in admin-ui.log
```
E, [2015-11-04T16:11:32.231855 #382] ERROR -- : [ -- ] : [ -- ] : Unexpected response code from sso_login_token_json is 400, message Bad Request, body {"error":"invalid_grant","error_description":"Invalid authorization code: EsVhmB"}
```

**Comment by rboykin** [comment]
Details in https://github.com/cloudfoundry-incubator/admin-ui/blob/master/README.md#setup-administration-ui-group-and-user-using-uaac on how to set up UAA client and give users group access.
