### ISSUE TITLE
Can only target Bosh Lite Director.Please use 'bosh target' before running this script

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-incubator/admin-ui#147]
I am trying to deploy bosh release for adminUI. It is failing as "Can only target Bosh Lite Director.Please use 'bosh target' before running this script." when i run ./make_manifest warden.I have installed cloud foundry using bosh.I have set the target and director name in my case is install-dev.Do I need to manually change EXPECTED_DIRECTOR_NAME value in make_manifest ?

**Comment by rboykin** [comment]
You should be opening this issue against https://github.com/cloudfoundry-community/admin-ui-boshrelease, not here
