### ISSUE TITLE
Log rotation is not supported

### ISSUE THREAD

**Issue by MNitta** [cloudfoundry-incubator/admin-ui#148]
Log rotation is not supported. The size of the log file becomes huge if admin-ui runs for a long time. Needed to manage log file size (log rotation and log file removal of old generation files automatically).

**Comment by rboykin** [comment]
Log rotation for the Admin UI (as is done for other Cloudfoundry components) is normally done external to the component.  For example, the bosh job for the admin ui would be a good place to accomplish this:  https://github.com/cloudfoundry-community/admin-ui-boshrelease
