### ISSUE TITLE
How to view logs of cloud controller and health manager in admin ui

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-incubator/admin-ui#149]
Currently I am able to view only admin_ui log.How to see logs of other component like cloud controller,health manager and others.I have following setting. Earlier I was under assumption that i can see all the logs by specifying path in attribute "log_files",I was wrong

log_file_sftp_keys: []
log_files: [/var/vcap/sys/log/cloud_controller_ng/*.log,/var/vcap/sys/log/admin_ui/admin_ui.log]
From doc I understand that it can show only those logs,that are local to vm where admin_ui is deployed.What value log_file_sftp_keys should hold ?
In the following link they are able to see all logs,seems they are copying the logs to one admin_ui machine. http://www.slideshare.net/platformcf/the-ibm-dashboard-for-operational-metrics Is there any way to view other logs also.Is copying logs from other vm to admin_ui vm is the option. Please guide me on this.

**Comment by rboykin** [comment]
You can use sftp to retrieve logs from other systems.  Look at the https://github.com/cloudfoundry-incubator/admin-ui/blob/master/README.md for configuration for log_files and log_file_sftp_keys.
