### ISSUE TITLE
sftp for log is not working for me

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-incubator/admin-ui#152]
I am trying to access cloud controlller log.I have modified admin_ui.yml file with this following setting  

log_file_sftp_keys: [/var/vcap/jobs/admin_ui/admin-key-devtest3]
log_files: [sftp://vcap@10.20.0.52/var/vcap/sys/log/cloud_controller_ng/*.log]

monit restart admin_ui.
admin_ui doesn't come up,Its failing.state goes to non monitored.
My private key file is present in /var/vcap/jobs/admin_ui/admin-key-devtest3 location.

Am I missing something here.Please guide me

**Comment by rboykin** [comment]
log_file_sftp_keys is an array of fully-qualified files, not a directory

**Comment by chrisrana** [comment]
admin-key-devtest3 is a private key

**Comment by chrisrana** [comment]
Here admin-key-devtest3 is a private key not directory.

**Comment by rboykin** [comment]
I was able to do this using the following:  http://askubuntu.com/questions/46930/how-can-i-set-up-password-less-ssh-login

I then used the private key in my sftp_keys and referenced the cloud controllers logs in my log_files via sftp just as you did.  I had to quote my entry within log_files. Without the quote, I get an error starting the admin ui:

Can't load config file: (/home/user/configs/230.yml): found unexpected ':' while scanning a plain scalar at line 17 column 13

I will update the README.md to include the quotes
