### ISSUE TITLE
memory consumption

### ISSUE THREAD

**Issue by sklevenz** [cloudfoundry-incubator/admin-ui#153]
Hi,

I am deploying the admin ui using this bosh release [1]. This release is using monit to watch admin ui process. Monit restarts the process after memory consumption threshold is hit. In [2] is a graph showing that a configured 1G limit is reached every 10 minutes which results in a restart by monit. At around 09:10 the limit was increased to 2G and process becomes stable now. But current memory consumption goes into range of 2 G.

I am not sure if this is maybe a memory leak. But with the increase of the Cloud Foundry usage (more users, orgs, spaces, apps ...) memory goes up.

To keep it short ;) is there a plan to get better scale for the admin ui?

Regards,
Stephan 

[1] https://github.com/cloudfoundry-community/admin-ui-boshrelease
[2] http://www.uppic.com/uploads/14564773131.png

**Comment by yatzek** [comment]
I am seeing the same problem, memory usage goes above 1G quite quickly and gets restarted.

**Comment by rboykin** [comment]
No current plans to change the admin ui in this regard.  I suggest you get https://github.com/cloudfoundry-community/admin-ui-boshrelease to increase its memory allocation.

**Comment by yatzek** [comment]
Hi,

Increasing memory allocation does not help - I did some debugging and it appears to be a problem
with how view models are being constructed. 
In my cf installation the biggest problem seem to be events - 7 days of events is about 30k records, every refresh builds up quickly exceeding 1GB of RAM. Please have a look at the attached heap analysis:

[heap_analyzed.txt](https://github.com/cloudfoundry-incubator/admin-ui/files/182763/heap_analyzed.txt)

you will see that there are plenty of objects allocated in lib/sequel/adapters/postgres.rb:669 and in events_view_model.rb in multiple places. Have a look at the "Duplicate Strings" section as well.

**Comment by yatzek** [comment]
@sklevenz - I am guessing it is because of large number of events in your installation, try changing event_days in your config to 1.

**Comment by sklevenz** [comment]
Thanks for the event tip. I will try this out.
