### ISSUE TITLE
Page not found for Service keys ,Indentity Zones,Indentity Providers

### ISSUE THREAD

**Issue by chrisrana** [cloudfoundry-incubator/admin-ui#154]
I am getting page not found for in the tab Service keys ,Indentity Zones,Indentity Providers.
Let me now how to resolve this issue.

**Comment by rboykin** [comment]
These are newer tabs.  If you are running with an older CloudFoundry installation, they will not be populated.

**Comment by chrisrana** [comment]
Which minimum cloud foundry version support  Indentity Zones,Indentity Providers.

**Comment by rboykin** [comment]
Looks like it's between 200 and 208 looking at commit history herein
