### ISSUE TITLE
A few tabs: This page requires data from service currently unavailable.

### ISSUE THREAD

**Issue by tomsherrod** [cloudfoundry-incubator/admin-ui#156]
Hi,

Deployed adminui against v230 CF. 
These tabs have the service currently unavailable message:
Organizations, Service Instances, Service Bindings, Service Keys, Service Plan Visibilities, Cells.

Pointers to what the problem may be? This is a Diego default backend, expected?

Thanks,
Tom

**Comment by rboykin** [comment]
The Organizations, Service Instances, Service Bindings, Service Keys and Service Plan Visibilities all come from the CCDB.  Check the log and ensure your Admin UI can access your configured ccdb_uri.

The Cell information ultimately comes through the /v2/info/doppler_logging_endpoint.  Ensure your configured cloud_controller_uri is correct and your configured uaa_client is correct and that client is created as documented in the Admin UI readme.

The Admin UI will handle both Diego backend and DEA backend.

**Comment by tomsherrod** [comment]
You are spot on.

The log indicates Doppler error, Unexpected response code: 401.

url="wss://doppler.domainname.com:4443/firehose/1459801858"  What are the
credentials being used for the doppler call, the ccdb_uri?

**Comment by rboykin** [comment]
The doppler firehose access uses your configured uaa client.  This client has to have the authority of doppler.firehose for this to work.  Check out the readme on setting up your admin ui client.  The doppler.firehose, clients.write and scim.write authorities have been recently added to the admin ui client.

**Comment by tomsherrod** [comment]
Correct again.
I can now see the cells and apps. The interface actually helped me find an
application that is still running, that shouldn't be.

A couple of tabs still have the error:
Organizations, Spaces, Service Instances, Service Bindings, Service Keys,
Service Plan, Service Plan Visibilities.
No errors in the admin_ui.log now.

**Comment by rboykin** [comment]
If tabs with earlier alphabetized names have content like applications, buildpacks, domains, etc. then it is possible that the data has just not yet been retrieved.  Retrieved in order here from the CCDB/UAADB:  https://github.com/cloudfoundry-incubator/admin-ui/blob/master/lib/admin/cc.rb#L24

**Comment by tomsherrod** [comment]
Thank you for your time and responding.
The tabs did not come up. I wiped out what was there and installed successfully, with all tabs.
