### ISSUE TITLE
Admin ui behind zuul

### ISSUE THREAD

**Issue by fghorbel** [cloudfoundry-incubator/admin-ui#161]
Hi, 

I have problem getting admin-ui working behind Zuul proxy. 
Only Get HTTP requests work fine. all other HTTP requests method such as (POST, DELETE, PUT, ...) don t work, they end up by 'Authorization failure' message from CF admin-ui log file and get redirected. 

Could anyone please help out to get this work. I would like to know why all non Get HTTP requests got rejected from admin-ui with the message "Authorization failure".     

By the way, when i hit the server directly, without going through Zuul, it works.

Thank you

**Comment by rboykin** [comment]
Closed due to inaction
