### ISSUE TITLE
Route service binding support?

### ISSUE THREAD

**Issue by cnelson** [cloudfoundry-incubator/admin-ui#164]
Does this application support inspecting [route service bindings](https://docs.cloudfoundry.org/services/route-services.html)? 

I am able to see a route service under the `Service Instances` tab, however the `Service Bindings` count is 0 even though it has been bound to a route with `cf bind-route-service`.

Is this expected behavior, a defect, or a missing feature?

**Comment by rboykin** [comment]
I have not yet added support for route services.

**Comment by rboykin** [comment]
@cnelson I am working on route services support now

**Comment by rboykin** [comment]
Route bindings support added with this commit:  https://github.com/cloudfoundry-incubator/admin-ui/commit/3611cee3c3be28ce664d296687fcf68a251765f7

**Comment by brittag** [comment]
Nice, thank you @rboykin! I use the Admin UI frequently and appreciate it.
