### ISSUE TITLE
Admin UI unresponsive/crashing when Firehose traffic is high

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry-incubator/admin-ui#166]
Hi,

we are running the Administration UI as application in our Cloud Foundry deployment. We have observed high CPU and memory usages which make the application unresponsive or even cause frequent reboots by the health manager. After some CPU and memory profiling, we have found out that the high event traffic (around 15000 events/sec) on the CF Firehose is responsible for the problems. Here is an excerpt from the CPU profiling:

 ```
==================================
  Mode: cpu(1000)
  Samples: 147470 (0.05% miss rate)
  GC: 38668 (26.22%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
    125132  (84.9%)       40882  (27.7%)     AdminUI::Doppler#doppler_message
     11344   (7.7%)       11344   (7.7%)     #<Module:0x0055cb7f3460e8>.read_varint
     99359  (67.4%)        4765   (3.2%)     WebSocket::Driver::Hybi#emit_frame
      6907   (4.7%)        4299   (2.9%)     block (2 levels) in define_setter
     56245  (38.1%)        3210   (2.2%)     #<Module:0x0055cb7f3460e8>.decode
     92739  (62.9%)        2719   (1.8%)     WebSocket::Driver::Hybi#emit_message
      3529   (2.4%)        2528   (1.7%)     Protobuf::Message.get_field
```

When we disable event processing by commenting out Doppler#doppler_message, the CPU usage drops from 100% to 20%-60%. On test landscapes with lower event traffic the CPU usage is also fine.

We have already scaled the app vertically as much as possible (runs in Diego). We have tried to run the app on JRuby instead of MRI to make better use multiple CPU cores, but some dependencies (mysql2) do not seem to be compatible. 

Another solution would be to offload the Firehose event processing to a separate Nozzle process. We have some Nozzles implemented in Go (similar to the [example-nozzle](https://github.com/cloudfoundry-incubator/example-nozzle)) which are performing fine. The Nozzle could handle the event parsing and filtering. The Admin UI could connect to a Websocket interface the Nozzle provides. To realize this solution, we would need a new configuration option to overwrite the default Doppler Websocket URL.

What do you think of this approach? Or do you see another solution?

Thanks and Best Regards,

  Jochen.

**Comment by rboykin** [comment]
I would prefer the loggregator supported some filtering on the firehose per https://github.com/cloudfoundry/loggregator/issues/155 and then the Admin UI would take advantage of it.

**Comment by ahevenor** [comment]
@rboykin We have plans to enable filtering of the firehose with our new gRPC/http2 API. It will be some time before we have http2 support in gorouter that would allow external clients like the admin-ui to use this feature.

**Comment by tyyko** [comment]
Hello @rboykin , while waiting for the loggregator features to be available we are implementing a nozzle to filter the unnecessary data before it reaches the admin-ui.

At the moment, admin-ui gets the doppler endpoint [directly from the CF API](https://github.com/cloudfoundry-incubator/admin-ui/blob/master/lib/admin/cc_rest_client.rb#L198-L199). 

Would you accept a contribution to allow the override of the doppler endpoint on an optional parameter in the [config.yml](https://github.com/cloudfoundry-incubator/admin-ui/blob/master/config/default.yml)?

**Comment by rboykin** [comment]
@tyyko Honestly, this would seem like a short-term solution to me that should be put in a private fork.  

What is your plan to secure this alternative doppler endpoint? It feels like a security exposure to me to pass the admin UI's admin-enabled token to this alternative doppler endpoint. Alternative to that is to provide credentials for the alternative doppler endpoint itself. If this is done, what would be needed to secure the alternative for your scenario? This is all assuming wss in my mind.

Also, would this alternative doppler endpoint include the capability of the client requesting the types of the records to be provided? Or, would the alternative doppler endpoint automatically just provide the correct filtering? The Admin UI needs ContainerMetrics and ValueMetrics only.  

The alternative doppler endpoint would have to follow the exact protocol of the actual doppler endpoint.

I am also not sure how I would automate testing for this proxy.

Given this would add a dependency outside of CF, this seems further questionable to me.

I recommend a private fork.

**Comment by tyyko** [comment]
Hi @rboykin, sorry for my late reply but I wanted to have some concrete results before continuing the discussion.

I agree on the fork suggestion, we could continue the discussion if the loggregator API will not come in the near future as planned or if they won't provide the same
advantages.

Scenario: Admin-ui and nozzle deployed as CF applications on special space with access to all necessary endpoints.

I implemented the switch to allow to override the doppler endpoint on the admin-ui and a Golang doppler nozzle.

The nozzle is simply a 'proxy' that forwards the subscriptionID and authToken received from the admin-ui and use it to connect to the real doppler; 
this happens when the admin-ui connects to the websocket server the nozzle provides.
On the nozzle we also filter out some useless metrics to send less nose to the admin-ui.

The following are some statistics for the nozzle to give you an idea of the volume of data and % of filtering.
```
2017-04-13T10:55:00.75+0200 [APP/PROC/WEB/0] OUT In the last 10 seconds
2017-04-13T10:55:00.75+0200 [APP/PROC/WEB/0] OUT sent messages:18691
2017-04-13T10:55:00.75+0200 [APP/PROC/WEB/0] OUT discarded messages:201300
2017-04-13T10:55:10.75+0200 [APP/PROC/WEB/0] OUT sent messages:14784
2017-04-13T10:55:10.75+0200 [APP/PROC/WEB/0] OUT In the last 10 seconds
2017-04-13T10:55:10.75+0200 [APP/PROC/WEB/0] OUT discarded messages:207937
2017-04-13T10:55:20.75+0200 [APP/PROC/WEB/0] OUT In the last 10 seconds
2017-04-13T10:55:20.75+0200 [APP/PROC/WEB/0] OUT discarded messages:203586
2017-04-13T10:55:20.75+0200 [APP/PROC/WEB/0] OUT sent messages:18273
2017-04-13T10:55:30.75+0200 [APP/PROC/WEB/0] OUT In the last 10 seconds
2017-04-13T10:55:30.75+0200 [APP/PROC/WEB/0] OUT discarded messages:198090
2017-04-13T10:55:30.75+0200 [APP/PROC/WEB/0] OUT sent messages:17675
```

While profiling the cpu usage of the admin-ui, the bottleneck has been moved from the doppler client to the database:
```
==================================
  Mode: wall(1000)
  Samples: 411474 (31.39% miss rate)
  GC: 92870 (22.57%)
==================================
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
    152008  (36.9%)       54039  (13.1%)     Sequel::Postgres::Dataset#fetch_rows
    197892  (48.1%)       39277   (9.5%)     #<Module:0x0055e42b8d5080>.run
    151724  (36.9%)       38305   (9.3%)     AdminUI::Doppler#doppler_message
     16109   (3.9%)       16109   (3.9%)     #<Module:0x0055e42b3e52c8>.read_varint
    154493  (37.5%)       13321   (3.2%)     AdminUI::CC#select
     13125   (3.2%)        7956   (1.9%)     block (2 levels) in define_setter
    139323  (33.9%)        6642   (1.6%)     WebSocket::Driver::Hybi#emit_frame
    157323  (38.2%)        5679   (1.4%)     WebSocket::Driver::Client#parse
     81618  (19.8%)        5651   (1.4%)     #<Module:0x0055e42b3e52c8>.decode
     10896   (2.6%)        5448   (1.3%)     AdminUI::EventsViewModel#do_items
      4701   (1.1%)        4701   (1.1%)     block (2 levels) in define_getter
      6024   (1.5%)        4500   (1.1%)     Protobuf::Message.get_field
    128828  (31.3%)        4391   (1.1%)     WebSocket::Driver::Hybi#emit_message
      8721   (2.1%)        4091   (1.0%)     AdminUI::ApplicationsViewModel#do_items
      8157   (2.0%)        4006   (1.0%)     AdminUI::ServiceBindingsViewModel#do_items
      3658   (0.9%)        3658   (0.9%)     Protobuf::Field::BaseField#repeated?
      7030   (1.7%)        3515   (0.9%)     AdminUI::RoutesViewModel#do_items
      9058   (2.2%)        3352   (0.8%)     AdminUI::SpacesViewModel#do_items
      7185   (1.7%)        3290   (0.8%)     AdminUI::UsersViewModel#do_items
      5453   (1.3%)        3016   (0.7%)     Protobuf::Message#clear!
      5640   (1.4%)        2856   (0.7%)     Faye::WebSocket::API::Event#initialize
      2757   (0.7%)        2757   (0.7%)     WebSocket::Extensions#valid_frame_rsv
      2707   (0.7%)        2707   (0.7%)     Protobuf::Field::StringField#decode
      5380   (1.3%)        2690   (0.7%)     AdminUI::ServiceInstancesViewModel#do_items
      2454   (0.6%)        2454   (0.6%)     WebSocket::Driver::Hybi::Message#initialize
      4684   (1.1%)        2342   (0.6%)     Sequel::Postgres::Adapter#execute_query
      7204   (1.8%)        2330   (0.6%)     Protobuf::Message#initialize
      4654   (1.1%)        2327   (0.6%)     AdminUI::SpaceRolesViewModel#add_rows
      3463   (0.8%)        2284   (0.6%)     WebSocket::Driver::StreamReader#read
      6152   (1.5%)        2243   (0.5%)     WebSocket::Driver::Hybi#parse_opcode
```
I still see spikes to 100% cpu usage on the patched admin-ui behind the nozzle, but not all the time like the vanilla one. It also feels faster while navigating through the tabs.

I cannot immediately share the code with you due to long and funny legal processes, but if anyone shows interest this might speed up the thing.

**Comment by rboykin** [comment]
Workaround provided by this PR:  https://github.com/cloudfoundry-incubator/admin-ui/pull/173
