### ISSUE TITLE
Datatables generates large URLs

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-incubator/admin-ui#167]
The ajax request for the organizations panel generates a large url (over 8kb, which is the default limit for nginx and apache). Is there a need for such long urls? It looks like many of the query parameters are generated by default by datatables, and might not actually be used server-side.

cc @cnelson

**Comment by rboykin** [comment]
This is a datatables-generated URL and is not modified by the Admin UI.

**Comment by mogul** [comment]
Are you closing this because you're fine with the admin UI breaking unexpectedly and invisibly depending on the data it's interacting with?

**Comment by rboykin** [comment]
I am closing this because this is a requirement of using DataTables and that is outside the control of the Admin UI.
