### ISSUE TITLE
30 cell limit?

### ISSUE THREAD

**Issue by tomsherrod** [cloudfoundry-incubator/admin-ui#169]
cf: v244
Running admin-ui successfully. 
New cells over 30 are not showing up.
Any particular area to look for debugging?

Thanks,
Tom

**Comment by rboykin** [comment]
@tomsherrod Check your config doppler_rollup_interval. Default is 30 seconds. Any component not reporting a value metric in 4 x doppler_rollup_interval is removed as stale. Try increasing the config amount to something like 600 or higher.

**Comment by tomsherrod** [comment]
600 worked. @rboykin Thank you!
