### ISSUE TITLE
Problem with accessing admin-ui

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#170]
Hi

I installed the admin-ui. In configuration file we mentioned "cloud_controller_uri: https://api.xxxx.com"
While accessing that from browser, we are getting error saying unable to fetch from https://api.xxxx.com/v2/info

While checking logs i found that its redirecting to our sso page and unable to do that.

> E, [2017-04-25T13:32:34.656110 #13633] ERROR -- : [ -- ] : [ -- ] : Error during redirect_to_login: >#RuntimeError: Unable to fetch from hhttps://api.xxxx.com/v2/info>
> E, [2017-04-25T13:32:34.656294 #13633] ERROR -- : [ -- ] : [ -- ] : /home/ubuntu/admin-ui/lib/admin/cc_rest_client.rb:182:in rescue in info' /home/ubuntu/admin-ui/lib/admin/cc_rest_client.rb:177:ininfo'
> /home/ubuntu/admin-ui/lib/admin/cc_rest_client.rb:96:in sso_login_redirect' /home/ubuntu/admin-ui/lib/admin/login.rb:20:inlogin_redirect_uri'
> /home/ubuntu/admin-ui/lib/admin/web.rb:2102:in redirect_to_login' /home/ubuntu/admin-ui/lib/admin/web.rb:49:inblock in class:Web'

Please help us how to achieve this

**Comment by rboykin** [comment]
@Akhilesh-Anb I note your log has hhttps.  Is this a typo on your part or does the config really have this value?  Outside of the admin ui on a command line, you should be able to do a curl https://api.xxxx.com/v2/info

**Comment by Akhilesh-Anb** [comment]
My bad its https only. Sorry for that.
My config file is with https://
I think there is a problem with proxy. I have disabled the proxy and its redirecting to SSO page.

Thank you for your response. I may approach you when i have a problem.

Thank you

**Comment by rboykin** [comment]
I am going to close this issue then.  Feel free to open another if a separate problem arises.
