### ISSUE TITLE
Unable to get data in few tabs

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#171]
Admin-UI is awesome and very helpful.

I have few tabs which are not getting data.
![image](https://cloud.githubusercontent.com/assets/12607627/25432377/d01bccce-2aa1-11e7-9c3d-37b365602e1a.png)

1) DEA
2) Organisation Isolation segments
3) Health Managers
4) Service Gateways
5) Security Group Spaces
6) SAML providers

There is no error. But, not getting the data.

---> There is one tab named "Staging security Groups spaces"
Here it showing me an error saying **This page requires data from services that are currently unavailable**

Appreciate your help.

Thank you

**Comment by rboykin** [comment]
@Akhilesh-Anb 

Most of these tabs will be empty depending on your environment.  
- If you don't have DEA's and only Diego Cells, the DEA's tab will be empty.  
- Organization Isolation Segments requires you to have affiliated an organization with an isolation segment.  
- Service Gateways will only show if you have old style community services.  
- Security Group Spaces and Staging Security Group Spaces will be empty if you have not affiliated.  
- SAML Providers will be empty if you have not set any up.  
- Security Group Spaces is fairly recent.  What version of cloudfoundry are you running?  If the concept of staging security group spaces not yet added to your version, you will see this error.

**Comment by Akhilesh-Anb** [comment]
Thank you @rboykin for your response.

I'm using OpsManager version of 1.9.4

**Comment by rboykin** [comment]
@Akhilesh-Anb Cannot tell the cloudfoundry version from that.  What does your api.xxxx.com/v2/info api_version field show for your cloudfoundry installation

**Comment by Akhilesh-Anb** [comment]
I'm sorry for that. I thought of OpsMan version.

"api_version":"2.65.0"

**Comment by rboykin** [comment]
@Akhilesh-Anb Thanks for the api_version.  That implies to me that staging security group spaces not yet in the base cloudfoundry code.  I believe it showed in the next published version:  2.68.0.  I see mentioned in docs starting here:  http://apidocs.cloudfoundry.org/250 for instance http://apidocs.cloudfoundry.org/250/security_groups/list_all_staging_spaces_for_the_security_group.html

**Comment by rboykin** [comment]
Closed due to being answered
