### ISSUE TITLE
Approvals tab

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#172]
HI,

I want to know what is the approvals tab in Admin-ui. 
Can you please let me know more information on that tab.

Appreciate your help

**Comment by rboykin** [comment]
@Akhilesh-Anb The approvals tab shows the contents of the UAADB table authz_approvals.

This table is populated when a UAA client is enabled for and authorized_grant_type of authorization_code and autoapprove is not set.

As an example of the code path which populates the authz_approvals table, see the service broker documentation for authorizing the service instance dashboard:  http://docs.cloudfoundry.org/services/dashboard-sso.html
