### ISSUE TITLE
Router not auto discovered

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry-incubator/admin-ui#174]
Hi

I need some support to set up admin-ui in my project. I am facing some problems.

When I click on tab 'Routers' always adds itself "0.0.0.0:8080" in the list, with status OFFLINE.
If I want to add my actual router I have to update the "data/data.json"

I am using ruby 2.3.1 instead 2.3.3. That could make a difference?

How would it be the proper way to set it up?
Best regards

**Comment by rboykin** [comment]
@rauizab The Router of "0.0.0.0:8080" is added by the varz case.  Bug in the router varz code.  What you likely need is to correctly configure your admin_ui_client's list of authorities.  Betting yours does not have doppler.firehose as is documented in the README and as a result cannot connect to your doppler_logging_endpoint firehose.  You can check you logs and see if your doppler is logging errors trying to connect to your doppler_logging_endpoint

**Comment by rauizab** [comment]
Hi
I think I did what you suggested to me, but still I get the same result.
Here is the result of my sql:
SELECT client_id, scope, authorities FROM uaa.oauth_client_detai

[oauth_client_details.xlsx](https://github.com/cloudfoundry-incubator/admin-ui/files/975992/oauth_client_details.xlsx)

What table should I update?
Best regards

**Comment by rboykin** [comment]
@rauizab I would suggest if you did indeed include the doppler.firehose within the authorities for the admin_ui_client and this is the client you use for the admin ui, then look to the admin_ui.log to see what errors you have received when the admin ui is attempting to connect with the doppler.

**Comment by rauizab** [comment]
I get:

Doppler error: #<Faye::WebSocket::API::ErrorEvent:0x00000002b7bc48 @type="error", @message=Errno::ECONNREFUSED, @bubbles=false, @cancelable=false, @current_target=#<Faye::WebSocket::Client:0x00000002be3c58 @url="wss://doppler.$MY_DOMAIN:4443/firehose/1493903205", @ready_state=0, @listeners={"open"=>[#<Proc:0x00000002b84758@/adminui/lib/admin/doppler.rb:183>], "message"=>[#<Proc:0x00000002b846b8@/adminui/lib/admin/doppler.rb:187>], "error"=>[#<Proc:0x00000002b84640@/adminui/lib/admin/doppler.rb:196>],  .............
....  a big stacktrace.

If the doppler is not accepting requests, why it could be? Can you give me some hint?
Best regards

**Comment by rboykin** [comment]
As a test vehicle for doppler, I would try to use the firehose plugin that works with the cf CLI.  If your cf client is defined as having a scope of doppler.firehose (it does looking at your earlier client details) and your logged-in cf CLI user is a member of the doppler.firehose group in UAA, then you can run "cf nozzle" and it will hit the same doppler firehose that the admin ui will hit.  This gets the admin ui out of the picture and greatly simplifies your doppler validation.  Here is a reference to the firehose plugin: https://github.com/cloudfoundry-community/firehose-plugin

**Comment by rauizab** [comment]
Hi
Thanks for your support. I will do as commented.

**Comment by rauizab** [comment]
Thanks, I see these ports open in my router:
22/tcp   open  ssh
80/tcp   open  http
111/tcp  open  rpcbind
443/tcp  open  https
8080/tcp open  http-proxy

I think port 4443 is closed. I will ask in the link you provided me.
Thanks

**Comment by rauizab** [comment]
On loggregator project https://github.com/cloudfoundry/loggregator/issues/261
