### ISSUE TITLE
Help to monitor DEA and other components

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry-incubator/admin-ui#175]
Hi

I am able to monitor the databases and cloud controller from cloud foundry  but not the other components.
Under tab "Components" I see only CloudController.
If a click on tab "DEAS", "Cells", "Health Managers", "Apps Instances" I got the message:
"This page requires data from services that are currently unavailable"

My configuration has:
monitored_components: [ALL]
cloud_controller_uri: http://api.${MY_DOMAIN}

I am using ruby 2.3.1 instead 2.3.3. That could make a difference?

Do you know what I could be doing wrong? Could it be because lack of roles for my admin_ui_client?
Best regards

**Comment by rauizab** [comment]
Duplicate from https://github.com/cloudfoundry-incubator/admin-ui/issues/171

**Comment by rboykin** [comment]
@rauizab This is a dup of https://github.com/cloudfoundry-incubator/admin-ui/issues/174 in that your admin_ui_client is likely not configured with the authority of doppler.firehose.

Closing as a dup
