### ISSUE TITLE
duplicated useres detection and deletion from UAAdb

### ISSUE THREAD

**Issue by gowrisankar22** [cloudfoundry-incubator/admin-ui#177]
Hi Colleagues,

I have experienced an issue that User exists twice with the same user name in the uaa db. Is there any script that does detection of ducplicated users and deletetion?

what is the best way you would suggest for the detection and deletion ?

Thanks in advance :) 

Thanks,
GS

**Comment by rboykin** [comment]
This is an issue best addressed to the UAA component of cloudfoundry:  https://github.com/cloudfoundry/uaa
