### ISSUE TITLE
Admin-UI with multiple endpoints?

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#179]
Hi @rboykin 

We have multiple environments of cloud foundry.
* Is there a way to monitor all the endpoints in the single admin-ui dashboard instead of 7 different dashboards for 7 environments.

* Is there a away to host admin-ui as a application in cloud foundry? If yes, could you please share us any documents on that.

Appreciate your help.

Thanks,
Akhilesh Appana

**Comment by rboykin** [comment]
@Akhilesh-Anb The admin ui only monitors a single CF installation.

See this prior issue with regards to running the admin ui as an application in cloud foundry: https://github.com/cloudfoundry-incubator/admin-ui/issues/145
