### ISSUE TITLE
Support for linux?

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#181]
Hi,

Will this work on Linux? If yes, could you please help us with Prerequisite Libraries that we need to install for using admin-ui.

Thanks,
Akhilesh Appana

**Comment by rboykin** [comment]
@Akhilesh-Anb Check the readme. I have the prereq libraries listed there:  https://github.com/cloudfoundry-incubator/admin-ui/blob/master/README.md#ubuntu-prerequisite-libraries

**Comment by Akhilesh-Anb** [comment]
Hi rboykin,

I have installed admin-ui in unix. Even you have mentioned the line "This has been tested on Ubuntu 10.04.4 64 bit, Ubuntu 12.04.3 64 bit, Ubuntu 13.04 64 bit and Ubuntu 14.04.3 64 bit."

Has this been tested on Linux? Now i need to install admin-ui in Linux machine.

when i do 

> yum install <libraries>
I'm getting the following error:
`No package git-core available.
No package build-essential available.
No package libreadline-dev available.
No package libssl-dev available.
No package libsqlite3-dev available.
No package libpq-dev available.
No package libmysqlclient-dev available.
Nothing to do
`

**Comment by rboykin** [comment]
@Akhilesh-Anb Ubuntu is a Linux variant. I use Ubuntu as that is the normal installation Linux variant for CloudFoundry. You will have to determine applicable libraries for your Linux variant.
