### ISSUE TITLE
Support for Ruby > 2.4.2

### ISSUE THREAD

**Issue by paolostivanin** [cloudfoundry-incubator/admin-ui#186]
Hello,
we are deploying admin-ui as a  CF application and, therefore, we are using the ruby-buildpack to deploy and run admin-ui.
Starting from [v1.7.18](https://github.com/cloudfoundry/ruby-buildpack/releases/tag/v1.7.18), supports for Ruby 2.4.2 was removed, meaning that we can no longer update the Ruby buildpack.

Do you have any plan to support a more recent Ruby version (eg 2.4.4)?

Thanks

**Comment by rboykin** [comment]
@paolostivanin Right now I am intentionally using the same level of ruby as the cloud controller: https://github.com/cloudfoundry/cloud_controller_ng/blob/master/.ruby-version

**Comment by paolostivanin** [comment]
Ok, I understand. Just for curiosity, do you plan to keep it that way or are you also planning to provide newer version?

**Comment by rboykin** [comment]
@paolostivanin I plan on keeping the ruby level in sync with the cloud controller.

**Comment by rboykin** [comment]
@paolostivanin Perhaps this issue on the cloud controller will result in some movement there: https://github.com/cloudfoundry/cloud_controller_ng/issues/1176

**Comment by rboykin** [comment]
@paolostivanin Upgraded admin ui to use ruby 2.4.5 via commit https://github.com/cloudfoundry-incubator/admin-ui/commit/6fb23db8e71a055b2090e031cbb879ad692dae06

**Comment by paolostivanin** [comment]
Thanks!

Pinging @michaelgrifalconi since I'm no longer working there :)
