### ISSUE TITLE
Doesn't show details org,space and other tabs

### ISSUE THREAD

**Issue by ichandan16** [cloudfoundry-incubator/admin-ui#188]
Hi ,

I did a successful push of the admin-ui to PCF. However, it doesn't show details in most of the tabs and the error I am getting is as below:

`This page requires data from services that are currently unavailable`

![image](https://user-images.githubusercontent.com/9046793/51413395-ce060700-1b3c-11e9-8113-87cce56423fd.png)

However, the  only details I am getting is from App Instances tab:

![image](https://user-images.githubusercontent.com/9046793/51413430-ed049900-1b3c-11e9-8cce-61a74ee277bd.png)

CCDB, UAADB, NATS details are correct. Here is my manifest.yml 

```
name: admin-ui
command: ruby bin/admin
buildpack: https://github.com/cloudfoundry/ruby-buildpack#v1.7.17
```

Appreciate any help.

Thanks,
Chandan

**Comment by rboykin** [comment]
@ichandan16 The fact you are getting data in the app instances tab indicates your UAA client is setup correctly. However, missing data in other tabs indicates your ccdb_uri, uaadb_uri and mbus are not set correctly in your admin ui configuration file. You can check out the admin_ui.log file and chances are you will see errors relating to accessing those items.

**Comment by ichandan16** [comment]
Thank you @rboykin . The mistake I had made was to take the mysql creds from PCF Internal MySQL mylogin.cnf file (root creds) which was not letting me connect to DBs.
Now I fetched them from credhub (https://docs.pivotal.io/pivotalcf/2-2/opsguide/internal-databases.html) and its working now.
Truly appreciate your help!

Thanks,
Chandan
