### ISSUE TITLE
Need help in Role Based access

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#190]
Hi,

We are creating a group and adding the users into that group who needs access. But this give me a view of my whole platform.

Is there a way to provide access according to the role what they have in our platform.
**Example**: As a admin user, i should be able to view the UI with all the information. when the development team user login, he should get an information in UI to which org and space etc.. he has access to.

Thanks,
Akhilesh Appana

**Comment by rboykin** [comment]
@Akhilesh-Anb The admin UI has two levels of roles. Both are admin level. First (`admin_ui.admin`) is all access which includes buttons on the various tabs. The second (`admin-ui.user`) just removes the button access. There is no finer-grained level of roles. The admin ui is not created for user-level access, but for admin-level access. You might look at https://github.com/cloudfoundry-incubator/stratos for a UI which gives user-level access.
