### ISSUE TITLE
Missing data in few tabs

### ISSUE THREAD

**Issue by Akhilesh-Anb** [cloudfoundry-incubator/admin-ui#196]
Hello,

I have deployed admin-ui and able to get all the data except  2 tabs mentioned below

1) Space Roles
2) Users

**Error**: This page requires data from services that are currently unavailable

I have only changed the following values in config:
```
doppler_rollup_interval: 100
varz_discovery_interval: 60
```

Thanks,
Akhilesh Appana

**Comment by rboykin** [comment]
@Akhilesh-Anb 

Look for `ERROR` in the admin_ui.log. This `log_file` value is identified in either the config/default.yaml or the config you specified (via `-c`) when running the admin ui.

Also look at your configuration value for uaadb_uri. Given your lack of data, you might have an incorrect value for that configuration value. You can verify this value is accurate if you can connect to the value of `uaadb_uri` via psql.

**Comment by Akhilesh-Anb** [comment]
Hi @rboykin ,

I tried checking the log file and couldn't see any `ERROR`. Attaching few logs here:

```
D, [2021-09-29T09:44:32.827597 #9] DEBUG -- : [ -- ] : [ -- ] : Caching view model space_roles data. Compilation time: 5.586e-05 seconds
D, [2021-09-29T09:44:32.827195 #9] DEBUG -- : [ -- ] : [ -- ] : [150 second interval] Starting view model users discovery...
D, [2021-09-29T09:44:32.828054 #9] DEBUG -- : [ -- ] : [ -- ] : Caching view model users data. Compilation time: 3.4854e-05 seconds
D, [2021-09-29T09:44:33.842864 #9] DEBUG -- : [ -- ] : [ -- ] : [300 second interval] Starting CC services discovery...
D, [2021-09-29T09:44:33.843023 #9] DEBUG -- : [ -- ] : [ -- ] : [300 second interval] Starting CC route_bindings discovery...
D, [2021-09-29T09:44:33.872582 #9] DEBUG -- : [ -- ] : [ -- ] : Caching CC services data. Count: 57. Retrieval time: 0.028661397 seconds
D, [2021-09-29T09:44:33.875190 #9] DEBUG -- : [ -- ] : [ -- ] : Caching CC route_bindings data. Count: 195. Retrieval time: 0.030594898 seconds
D, [2021-09-29T09:44:38.542350 #9] DEBUG -- : [ -- ] : [ -- ] : [300 second interval] Starting CC service_bindings discovery...
D, [2021-09-29T09:44:38.542485 #9] DEBUG -- : [ -- ] : [ -- ] : [300 second interval] Starting CC buildpack_lifecycle_data discovery...
D, [2021-09-29T09:44:43.631969 #9] DEBUG -- : [ -- ] : [ -- ] : [150 second interval] Starting view model space_roles discovery...
D, [2021-09-29T09:44:43.632573 #9] DEBUG -- : [ -- ] : [ -- ] : Caching view model space_roles data. Compilation time: 5.9717e-05 seconds
D, [2021-09-29T09:44:43.632124 #9] DEBUG -- : [ -- ] : [ -- ] : [150 second interval] Starting view model users discovery...
D, [2021-09-29T09:44:43.819994 #9] DEBUG -- : [ -- ] : [ -- ] : Caching view model users data. Compilation time: 7.6525e-05 seconds
```

I'm able to login manually to uaa database with creds provided in config file. 
Also I'm able to see other tabs data like Organization_roles, clients, groups, group_members etc...

not sure why only Users tab and space_roles tab is not getting data

thanks,
Akhilesh Appana

**Comment by Akhilesh-Anb** [comment]
![image](https://user-images.githubusercontent.com/12607627/135251937-47bb8cfb-ac6f-45c8-a688-c7d456116a5c.png)

Able to see users information under Group_members tab but not in actual USERS tab

![image](https://user-images.githubusercontent.com/12607627/135252094-0d1d81d7-c284-4630-91f6-c8b88094d060.png)

**Comment by rboykin** [comment]
@Akhilesh-Anb I think I figured out the problem and will attempt to have a fix in the next handful of days.

**Comment by rboykin** [comment]
Fixed with commit https://github.com/cloudfoundry-incubator/admin-ui/commit/def19deb789f4a38af5e4b87fdc1716fa9046dca
