### ISSUE TITLE
Datatables Upgrade v2.0.8

### ISSUE THREAD

**Issue by MythodeaLoL** [cloudfoundry-incubator/admin-ui#198]
could you update the admin-ui to add the datatable editor update?

**Comment by rboykin** [comment]
@MythodeaLoL I don't want to update DataTables piecemeal. Once DataTables includes this update and publishes its own release, I will pull in that new DataTables release. I suggest you make this request in the DataTablesSrc repository; https://github.com/DataTables/DataTablesSrc
